### ISSUE TITLE
one nameserver

### ISSUE THREAD

**Issue by WhyMan1** [Phoenix-999/DNS-WebRTC-Leak-Shield#2]
اینجا دو تا باشن بهتر نیست؟

# Primary DNS server IP address (Cloudflare DNS)
nameserver 1.0.0.1

**Comment by Phoenix-999** [comment]
این قسمت ` /etc/resolv.conf` هرچی سبک‌تر باشه بهتر هست  دقیقاً همون کارو می‌کنه فرقی آنچنان نداره

![Screenshot 2024-07-24 at 17 33 02](https://github.com/user-attachments/assets/aafc46e1-2a59-4c96-9e1e-0daa5001008a)

در قسمت `/etc/systemd/resolved.conf` هم به علت اینکه DNSOverTLS=yes روشن هست بهترین گزینه این خواهد بود

![Screenshot 2024-07-24 at 17 38 24](https://github.com/user-attachments/assets/86e30a5c-f69c-46ff-a77a-4aba70729d4f)

**Comment by WhyMan1** [comment]
متاسفانه مشکل ایجاد کرد و مجبور شدم برش دارم از سرور احتمالا باید بیشتر صحبت کنیم
گروهی چیزی داری شما؟

**Comment by Phoenix-999** [comment]
@WhyMan1 
مشکل دقیقاً چی هست توضیح بدید یا اسکرین شات بفرستید
